# Generated by Django 2.2.1 on 2019-07-27 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Asignatura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('ap_pat', models.CharField(max_length=50, null=True)),
                ('ap_mat', models.CharField(max_length=50, null=True)),
                ('edad', models.IntegerField()),
                ('address', models.CharField(max_length=50, null=True)),
                ('correo', models.CharField(max_length=50, null=True)),
                ('genero', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('asignature', models.ForeignKey(null=True, on_delete=models.SET(-1), to='Asignatura.Asignatura')),
            ],
            options={
                'db_table': 'Profesor',
            },
        ),
    ]
